[phases.setup]
nixPkgs = ["python311", "gcc", "sqlite"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python main.py"
